### 

POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Jack",
  "email": "jack@example.com",
  "password": "abc"
}

### -> Update extra user info (user identifier on th URL)

PUT http://localhost:3000/users/5/profile
Content-Type: application/json

{
  "course_id": 1,
  "university_id": 1,
  "address": "123 Main St, City, Country",
  "latitude": 40.7128,
  "longitude": -74.0060,
  "role_id": 2
}

### -> Clear all tables data

POST http://localhost:3000/clear

### -> Clear users data

POST http://localhost:3000/clear/users

### -> Get user data without token
GET http://localhost:3000/users

### -> Get user data with valid token
GET http://localhost:3000/usersWithToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqYWNrQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwMDkwNjUyLCJleHAiOjE3NjAwOTE1NTJ9.Fn84YOTv9P20JdPTa-cpaTfPcvTRmu_Cp9vKzDZVdSI

### -> Get new access token with refresh token

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbGljZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MDA4NzE1OX0.WvFS0dp5fhP9JiHBNBsHCDQBzG36IJU5NkArF9hK9jE"
}

### -> Delete refresh token on logout

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbGljZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MDA4NzE1OX0.WvFS0dp5fhP9JiHBNBsHCDQBzG36IJU5NkArF9hK9jE"
}

### -> Login to get access and refresh tokens

POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "jack@example.com",
  "password": "abc"
}